### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mkoert** [gonzalo123/yml2pimple#16]
Looking to use this in a small mvc wrapper for silex. I was wondering what the license for the project?

**Comment by gonzalo123** [comment]
I'm not a not a license expert. I Normally y use MIT but almost always I forget to create the license file. 

Basically is one kind of free as free beer license (AFAIK MIT is the the most permissive one). 

Thanks to your issue I just discover that github allow me to create license files with a simple template. It's perfect for lazy-legal-terms developers like me.

Thanks!
